name: solve_24_game
description: The 24 puzzle is an arithmetical puzzle in which the objective is to find a way to manipulate four integers so that the end result is 24. For example, for the numbers 4, 7, 8, 8, a possible solution is (7 - (8 รท 8)) x 4 = 24
version: 1.0.0
homepage: https://github.com/Martoxdlol/dart_solve_24_game
repository: https://github.com/Martoxdlol/dart_solve_24_game
documentation: https://github.com/Martoxdlol/dart_solve_24_game/blob/main/README.md

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ^3.1.2

dependencies:
  trotter: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
